# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmActiChampConfig.ui'
#
# Created: Wed Jun 05 12:00:50 2013
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmActiChampConfig(object):
    def setupUi(self, frmActiChampConfig):
        frmActiChampConfig.setObjectName("frmActiChampConfig")
        frmActiChampConfig.resize(772, 607)
        frmActiChampConfig.setFrameShape(QtGui.QFrame.StyledPanel)
        frmActiChampConfig.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(frmActiChampConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(frmActiChampConfig)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tableViewChannels = QtGui.QTableView(frmActiChampConfig)
        self.tableViewChannels.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.tableViewChannels.setAlternatingRowColors(True)
        self.tableViewChannels.setObjectName("tableViewChannels")
        self.tableViewChannels.horizontalHeader().setCascadingSectionResizes(False)
        self.tableViewChannels.horizontalHeader().setStretchLastSection(True)
        self.tableViewChannels.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableViewChannels, 1, 0, 1, 1)
        self.tableViewAux = QtGui.QTableView(frmActiChampConfig)
        self.tableViewAux.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.tableViewAux.setAlternatingRowColors(True)
        self.tableViewAux.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableViewAux.setObjectName("tableViewAux")
        self.tableViewAux.horizontalHeader().setStretchLastSection(True)
        self.tableViewAux.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableViewAux, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(frmActiChampConfig)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(6, -1, 6, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBoxSampleRate = QtGui.QComboBox(frmActiChampConfig)
        self.comboBoxSampleRate.setObjectName("comboBoxSampleRate")
        self.gridLayout_2.addWidget(self.comboBoxSampleRate, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(frmActiChampConfig)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(frmActiChampConfig)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(frmActiChampConfig)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBoxEmulation = QtGui.QComboBox(frmActiChampConfig)
        self.comboBoxEmulation.setObjectName("comboBoxEmulation")
        self.comboBoxEmulation.addItem(QtCore.QString())
        self.comboBoxEmulation.addItem(QtCore.QString())
        self.comboBoxEmulation.addItem(QtCore.QString())
        self.comboBoxEmulation.addItem(QtCore.QString())
        self.comboBoxEmulation.addItem(QtCore.QString())
        self.comboBoxEmulation.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.comboBoxEmulation, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(frmActiChampConfig)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_Simulated = QtGui.QLabel(frmActiChampConfig)
        self.label_Simulated.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Simulated.setMargin(5)
        self.label_Simulated.setObjectName("label_Simulated")
        self.horizontalLayout.addWidget(self.label_Simulated)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_Reference = QtGui.QLabel(frmActiChampConfig)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_Reference.setPalette(palette)
        self.label_Reference.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reference.setObjectName("label_Reference")
        self.verticalLayout.addWidget(self.label_Reference)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)

        self.retranslateUi(frmActiChampConfig)
        QtCore.QMetaObject.connectSlotsByName(frmActiChampConfig)

    def retranslateUi(self, frmActiChampConfig):
        frmActiChampConfig.setWindowTitle(QtGui.QApplication.translate("frmActiChampConfig", "Amplifier", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmActiChampConfig", "EEG Channel Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmActiChampConfig", "AUX Channel Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmActiChampConfig", "Sampling Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmActiChampConfig", "[Hz]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmActiChampConfig", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEmulation.setItemText(0, QtGui.QApplication.translate("frmActiChampConfig", "off", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEmulation.setItemText(1, QtGui.QApplication.translate("frmActiChampConfig", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEmulation.setItemText(2, QtGui.QApplication.translate("frmActiChampConfig", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEmulation.setItemText(3, QtGui.QApplication.translate("frmActiChampConfig", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEmulation.setItemText(4, QtGui.QApplication.translate("frmActiChampConfig", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxEmulation.setItemText(5, QtGui.QApplication.translate("frmActiChampConfig", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmActiChampConfig", "Module(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Simulated.setText(QtGui.QApplication.translate("frmActiChampConfig", "(simulating 32 channel(s))", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Reference.setText(QtGui.QApplication.translate("frmActiChampConfig", "Selected Reference:", None, QtGui.QApplication.UnicodeUTF8))

