# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmFilterConfig.ui'
#
# Created: Wed Jun 05 12:00:50 2013
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmFilterConfig(object):
    def setupUi(self, frmFilterConfig):
        frmFilterConfig.setObjectName("frmFilterConfig")
        frmFilterConfig.resize(690, 423)
        frmFilterConfig.setFrameShape(QtGui.QFrame.StyledPanel)
        frmFilterConfig.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout_2 = QtGui.QGridLayout(frmFilterConfig)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(frmFilterConfig)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.tableView = QtGui.QTableView(frmFilterConfig)
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableView, 5, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(frmFilterConfig)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(frmFilterConfig)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(frmFilterConfig)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.checkBoxEegNotch = QtGui.QCheckBox(frmFilterConfig)
        self.checkBoxEegNotch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxEegNotch.setObjectName("checkBoxEegNotch")
        self.gridLayout.addWidget(self.checkBoxEegNotch, 1, 2, 1, 1)
        self.comboBoxEegLowpass = QtGui.QComboBox(frmFilterConfig)
        self.comboBoxEegLowpass.setObjectName("comboBoxEegLowpass")
        self.gridLayout.addWidget(self.comboBoxEegLowpass, 1, 0, 1, 1)
        self.comboBoxEegHighpass = QtGui.QComboBox(frmFilterConfig)
        self.comboBoxEegHighpass.setObjectName("comboBoxEegHighpass")
        self.gridLayout.addWidget(self.comboBoxEegHighpass, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(frmFilterConfig)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(frmFilterConfig)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(frmFilterConfig)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 2, 1, 1)
        self.comboBox_Notch = QtGui.QComboBox(frmFilterConfig)
        self.comboBox_Notch.setMaxVisibleItems(2)
        self.comboBox_Notch.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox_Notch.setObjectName("comboBox_Notch")
        self.comboBox_Notch.addItem(QtCore.QString())
        self.comboBox_Notch.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.comboBox_Notch, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(frmFilterConfig)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 1, 1, 1)

        self.retranslateUi(frmFilterConfig)
        self.comboBox_Notch.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmFilterConfig)

    def retranslateUi(self, frmFilterConfig):
        frmFilterConfig.setWindowTitle(QtGui.QApplication.translate("frmFilterConfig", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmFilterConfig", "AUX Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmFilterConfig", "High Cutoff [Hz]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmFilterConfig", "Low Cutoff [Hz]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmFilterConfig", "Notchfilter", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxEegNotch.setText(QtGui.QApplication.translate("frmFilterConfig", "on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmFilterConfig", "EEG Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmFilterConfig", "Frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmFilterConfig", "[Hz]", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Notch.setItemText(0, QtGui.QApplication.translate("frmFilterConfig", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Notch.setItemText(1, QtGui.QApplication.translate("frmFilterConfig", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("frmFilterConfig", "Notchfilter", None, QtGui.QApplication.UnicodeUTF8))

