# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMainStatusBar.ui'
#
# Created: Wed Jun 05 12:00:50 2013
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmStatusBar(object):
    def setupUi(self, frmStatusBar):
        frmStatusBar.setObjectName("frmStatusBar")
        frmStatusBar.resize(903, 43)
        self.horizontalLayout = QtGui.QHBoxLayout(frmStatusBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelInfo = QtGui.QLabel(frmStatusBar)
        self.labelInfo.setFrameShape(QtGui.QFrame.Panel)
        self.labelInfo.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelInfo.setObjectName("labelInfo")
        self.horizontalLayout.addWidget(self.labelInfo)
        self.labelStatus_1 = QtGui.QLabel(frmStatusBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus_1.sizePolicy().hasHeightForWidth())
        self.labelStatus_1.setSizePolicy(sizePolicy)
        self.labelStatus_1.setMinimumSize(QtCore.QSize(50, 0))
        self.labelStatus_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelStatus_1.setBaseSize(QtCore.QSize(0, 0))
        self.labelStatus_1.setFrameShape(QtGui.QFrame.Panel)
        self.labelStatus_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelStatus_1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus_1.setMargin(2)
        self.labelStatus_1.setObjectName("labelStatus_1")
        self.horizontalLayout.addWidget(self.labelStatus_1)
        self.labelStatus_2 = QtGui.QLabel(frmStatusBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus_2.sizePolicy().hasHeightForWidth())
        self.labelStatus_2.setSizePolicy(sizePolicy)
        self.labelStatus_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.labelStatus_2.setFrameShape(QtGui.QFrame.Panel)
        self.labelStatus_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelStatus_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus_2.setWordWrap(True)
        self.labelStatus_2.setObjectName("labelStatus_2")
        self.horizontalLayout.addWidget(self.labelStatus_2)
        self.labelStatus_3 = QtGui.QLabel(frmStatusBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus_3.sizePolicy().hasHeightForWidth())
        self.labelStatus_3.setSizePolicy(sizePolicy)
        self.labelStatus_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.labelStatus_3.setFrameShape(QtGui.QFrame.Panel)
        self.labelStatus_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelStatus_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus_3.setObjectName("labelStatus_3")
        self.horizontalLayout.addWidget(self.labelStatus_3)
        self.labelStatus_4 = QtGui.QLabel(frmStatusBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus_4.sizePolicy().hasHeightForWidth())
        self.labelStatus_4.setSizePolicy(sizePolicy)
        self.labelStatus_4.setMinimumSize(QtCore.QSize(60, 0))
        self.labelStatus_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelStatus_4.setFrameShape(QtGui.QFrame.Panel)
        self.labelStatus_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelStatus_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus_4.setObjectName("labelStatus_4")
        self.horizontalLayout.addWidget(self.labelStatus_4)
        self.progressBarUtilization = QtGui.QProgressBar(frmStatusBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarUtilization.sizePolicy().hasHeightForWidth())
        self.progressBarUtilization.setSizePolicy(sizePolicy)
        self.progressBarUtilization.setMaximumSize(QtCore.QSize(150, 16777215))
        self.progressBarUtilization.setMaximum(100)
        self.progressBarUtilization.setProperty("value", QtCore.QVariant(20))
        self.progressBarUtilization.setInvertedAppearance(False)
        self.progressBarUtilization.setObjectName("progressBarUtilization")
        self.horizontalLayout.addWidget(self.progressBarUtilization)

        self.retranslateUi(frmStatusBar)
        QtCore.QMetaObject.connectSlotsByName(frmStatusBar)

    def retranslateUi(self, frmStatusBar):
        frmStatusBar.setWindowTitle(QtGui.QApplication.translate("frmStatusBar", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo.setToolTip(QtGui.QApplication.translate("frmStatusBar", "Click here to get the message history", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo.setText(QtGui.QApplication.translate("frmStatusBar", "Brain Products GmbH", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatus_1.setToolTip(QtGui.QApplication.translate("frmStatusBar", "Sampling Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatus_2.setToolTip(QtGui.QApplication.translate("frmStatusBar", "Total number of channels and reference channels", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatus_3.setToolTip(QtGui.QApplication.translate("frmStatusBar", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatus_4.setToolTip(QtGui.QApplication.translate("frmStatusBar", "Battery Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBarUtilization.setFormat(QtGui.QApplication.translate("frmStatusBar", "%v% Utilization", None, QtGui.QApplication.UnicodeUTF8))

