# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMain.ui'
#
# Created: Wed Jun 05 12:00:50 2013
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 604)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/PyCorder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_SignalPane = QtGui.QHBoxLayout()
        self.horizontalLayout_SignalPane.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_SignalPane.setObjectName("horizontalLayout_SignalPane")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_SignalPane.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.horizontalLayout_SignalPane)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 300, 533))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_OnlinePane = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_OnlinePane.setObjectName("verticalLayout_OnlinePane")
        self.pushButtonConfiguration = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonConfiguration.setStyleSheet("text-align: left; padding-left: 10px; padding-top: 5px; padding-bottom: 5px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/process.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonConfiguration.setIcon(icon1)
        self.pushButtonConfiguration.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonConfiguration.setObjectName("pushButtonConfiguration")
        self.verticalLayout_OnlinePane.addWidget(self.pushButtonConfiguration)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_OnlinePane.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 27))
        self.menubar.setObjectName("menubar")
        self.menuApplication = QtGui.QMenu(self.menubar)
        self.menuApplication.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.menuApplication.setTearOffEnabled(False)
        self.menuApplication.setObjectName("menuApplication")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionShow_Log = QtGui.QAction(MainWindow)
        self.actionShow_Log.setObjectName("actionShow_Log")
        self.actionLoad_Configuration = QtGui.QAction(MainWindow)
        self.actionLoad_Configuration.setObjectName("actionLoad_Configuration")
        self.actionSave_Configuration = QtGui.QAction(MainWindow)
        self.actionSave_Configuration.setObjectName("actionSave_Configuration")
        self.actionDefault_Configuration = QtGui.QAction(MainWindow)
        self.actionDefault_Configuration.setObjectName("actionDefault_Configuration")
        self.menuApplication.addAction(self.actionLoad_Configuration)
        self.menuApplication.addAction(self.actionSave_Configuration)
        self.menuApplication.addAction(self.actionDefault_Configuration)
        self.menuApplication.addSeparator()
        self.menuApplication.addAction(self.actionShow_Log)
        self.menuApplication.addSeparator()
        self.menuApplication.addAction(self.actionQuit)
        self.menubar.addAction(self.menuApplication.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyCorder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonConfiguration.setText(QtGui.QApplication.translate("MainWindow", "Configuration ...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuApplication.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Log.setText(QtGui.QApplication.translate("MainWindow", "Show Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Configuration.setText(QtGui.QApplication.translate("MainWindow", "Load Configuration ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Configuration.setText(QtGui.QApplication.translate("MainWindow", "Save Configuration ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_Configuration.setText(QtGui.QApplication.translate("MainWindow", "Reset Configuration", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
