# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmStorageVisionConfig.ui'
#
# Created: Wed Jun 05 12:00:50 2013
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmStorageVisionConfig(object):
    def setupUi(self, frmStorageVisionConfig):
        frmStorageVisionConfig.setObjectName("frmStorageVisionConfig")
        frmStorageVisionConfig.resize(622, 325)
        frmStorageVisionConfig.setFrameShape(QtGui.QFrame.StyledPanel)
        frmStorageVisionConfig.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout_2 = QtGui.QGridLayout(frmStorageVisionConfig)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(frmStorageVisionConfig)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditFolder = QtGui.QLineEdit(frmStorageVisionConfig)
        self.lineEditFolder.setObjectName("lineEditFolder")
        self.horizontalLayout.addWidget(self.lineEditFolder)
        self.pushButtonBrowse = QtGui.QPushButton(frmStorageVisionConfig)
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.horizontalLayout.addWidget(self.pushButtonBrowse)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.checkBoxAutoFile = QtGui.QCheckBox(frmStorageVisionConfig)
        self.checkBoxAutoFile.setObjectName("checkBoxAutoFile")
        self.gridLayout_2.addWidget(self.checkBoxAutoFile, 2, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(frmStorageVisionConfig)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.lineEditPrefix = QtGui.QLineEdit(frmStorageVisionConfig)
        self.lineEditPrefix.setObjectName("lineEditPrefix")
        self.gridLayout.addWidget(self.lineEditPrefix, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(frmStorageVisionConfig)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.lineEditCounterSize = QtGui.QLineEdit(frmStorageVisionConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCounterSize.sizePolicy().hasHeightForWidth())
        self.lineEditCounterSize.setSizePolicy(sizePolicy)
        self.lineEditCounterSize.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditCounterSize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCounterSize.setObjectName("lineEditCounterSize")
        self.gridLayout.addWidget(self.lineEditCounterSize, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(frmStorageVisionConfig)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.labelExample = QtGui.QLabel(frmStorageVisionConfig)
        self.labelExample.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelExample.sizePolicy().hasHeightForWidth())
        self.labelExample.setSizePolicy(sizePolicy)
        self.labelExample.setMinimumSize(QtCore.QSize(0, 23))
        self.labelExample.setFrameShape(QtGui.QFrame.Panel)
        self.labelExample.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelExample.setObjectName("labelExample")
        self.gridLayout.addWidget(self.labelExample, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(frmStorageVisionConfig)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEditSpace = QtGui.QLineEdit(frmStorageVisionConfig)
        self.lineEditSpace.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEditSpace.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSpace.setObjectName("lineEditSpace")
        self.horizontalLayout_2.addWidget(self.lineEditSpace)
        self.label_6 = QtGui.QLabel(frmStorageVisionConfig)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)

        self.retranslateUi(frmStorageVisionConfig)
        QtCore.QMetaObject.connectSlotsByName(frmStorageVisionConfig)

    def retranslateUi(self, frmStorageVisionConfig):
        frmStorageVisionConfig.setWindowTitle(QtGui.QApplication.translate("frmStorageVisionConfig", "Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "Data File Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowse.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "Browse ...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoFile.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "Automatic Filename Generation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "Counter Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "Example", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "Minimum required disk space ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmStorageVisionConfig", "[GB]", None, QtGui.QApplication.UnicodeUTF8))

