# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmScopeOnline.ui'
#
# Created: Wed Jun 05 12:00:50 2013
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmScopeOnline(object):
    def setupUi(self, frmScopeOnline):
        frmScopeOnline.setObjectName("frmScopeOnline")
        frmScopeOnline.resize(280, 186)
        frmScopeOnline.setFrameShape(QtGui.QFrame.Panel)
        frmScopeOnline.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(frmScopeOnline)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(frmScopeOnline)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_OnlineScope = QtGui.QGridLayout()
        self.gridLayout_OnlineScope.setContentsMargins(4, -1, 4, -1)
        self.gridLayout_OnlineScope.setHorizontalSpacing(12)
        self.gridLayout_OnlineScope.setObjectName("gridLayout_OnlineScope")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_OnlineScope.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxTime = QtGui.QComboBox(self.groupBox)
        self.comboBoxTime.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBoxTime.setObjectName("comboBoxTime")
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.comboBoxTime.addItem(QtCore.QString())
        self.gridLayout_OnlineScope.addWidget(self.comboBoxTime, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_OnlineScope.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxScale = QtGui.QComboBox(self.groupBox)
        self.comboBoxScale.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBoxScale.setMaxVisibleItems(16)
        self.comboBoxScale.setObjectName("comboBoxScale")
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.comboBoxScale.addItem(QtCore.QString())
        self.gridLayout_OnlineScope.addWidget(self.comboBoxScale, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_OnlineScope.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_OnlineScope.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_OnlineScope.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboBoxChannels = QtGui.QComboBox(self.groupBox)
        self.comboBoxChannels.setMaximumSize(QtCore.QSize(400, 16777215))
        self.comboBoxChannels.setMaxVisibleItems(20)
        self.comboBoxChannels.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxChannels.setObjectName("comboBoxChannels")
        self.gridLayout_OnlineScope.addWidget(self.comboBoxChannels, 2, 1, 1, 1)
        self.comboBoxGroupSize = QtGui.QComboBox(self.groupBox)
        self.comboBoxGroupSize.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBoxGroupSize.setObjectName("comboBoxGroupSize")
        self.comboBoxGroupSize.addItem(QtCore.QString())
        self.comboBoxGroupSize.addItem(QtCore.QString())
        self.comboBoxGroupSize.addItem(QtCore.QString())
        self.comboBoxGroupSize.addItem(QtCore.QString())
        self.comboBoxGroupSize.addItem(QtCore.QString())
        self.comboBoxGroupSize.addItem(QtCore.QString())
        self.gridLayout_OnlineScope.addWidget(self.comboBoxGroupSize, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_OnlineScope, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxBaseline = QtGui.QCheckBox(self.groupBox)
        self.checkBoxBaseline.setObjectName("checkBoxBaseline")
        self.horizontalLayout.addWidget(self.checkBoxBaseline)
        self.pushButton_Now = QtGui.QPushButton(self.groupBox)
        self.pushButton_Now.setObjectName("pushButton_Now")
        self.horizontalLayout.addWidget(self.pushButton_Now)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(frmScopeOnline)
        self.comboBoxTime.setCurrentIndex(6)
        self.comboBoxScale.setCurrentIndex(7)
        self.comboBoxChannels.setCurrentIndex(-1)
        self.comboBoxGroupSize.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmScopeOnline)

    def retranslateUi(self, frmScopeOnline):
        frmScopeOnline.setWindowTitle(QtGui.QApplication.translate("frmScopeOnline", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("frmScopeOnline", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmScopeOnline", "Timebase", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(0, QtGui.QApplication.translate("frmScopeOnline", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(1, QtGui.QApplication.translate("frmScopeOnline", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(2, QtGui.QApplication.translate("frmScopeOnline", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(3, QtGui.QApplication.translate("frmScopeOnline", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(4, QtGui.QApplication.translate("frmScopeOnline", "2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(5, QtGui.QApplication.translate("frmScopeOnline", "5.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(6, QtGui.QApplication.translate("frmScopeOnline", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(7, QtGui.QApplication.translate("frmScopeOnline", "20.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxTime.setItemText(8, QtGui.QApplication.translate("frmScopeOnline", "50.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmScopeOnline", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(0, QtGui.QApplication.translate("frmScopeOnline", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(1, QtGui.QApplication.translate("frmScopeOnline", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(2, QtGui.QApplication.translate("frmScopeOnline", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(3, QtGui.QApplication.translate("frmScopeOnline", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(4, QtGui.QApplication.translate("frmScopeOnline", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(5, QtGui.QApplication.translate("frmScopeOnline", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(6, QtGui.QApplication.translate("frmScopeOnline", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(7, QtGui.QApplication.translate("frmScopeOnline", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(8, QtGui.QApplication.translate("frmScopeOnline", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(9, QtGui.QApplication.translate("frmScopeOnline", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(10, QtGui.QApplication.translate("frmScopeOnline", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(11, QtGui.QApplication.translate("frmScopeOnline", "2000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(12, QtGui.QApplication.translate("frmScopeOnline", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(13, QtGui.QApplication.translate("frmScopeOnline", "10000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(14, QtGui.QApplication.translate("frmScopeOnline", "20000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxScale.setItemText(15, QtGui.QApplication.translate("frmScopeOnline", "50000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmScopeOnline", "/Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmScopeOnline", "/Div", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmScopeOnline", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxGroupSize.setItemText(0, QtGui.QApplication.translate("frmScopeOnline", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxGroupSize.setItemText(1, QtGui.QApplication.translate("frmScopeOnline", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxGroupSize.setItemText(2, QtGui.QApplication.translate("frmScopeOnline", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxGroupSize.setItemText(3, QtGui.QApplication.translate("frmScopeOnline", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxGroupSize.setItemText(4, QtGui.QApplication.translate("frmScopeOnline", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxGroupSize.setItemText(5, QtGui.QApplication.translate("frmScopeOnline", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBaseline.setText(QtGui.QApplication.translate("frmScopeOnline", "Baseline Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Now.setText(QtGui.QApplication.translate("frmScopeOnline", "Now", None, QtGui.QApplication.UnicodeUTF8))

